name: Generate Docs
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
      - name: Install dependencies 🔧
        run: pip3 install sphinx sphinxawesome-theme sphinx-sitemap myst-parser

#      - name: Configure GitHub Pages
#        uses: actions/configure-pages@v3

      - name: Build Documentation 🧱
        uses: sphinx-notes/pages@v3
        with:
          checkout: true
          publish: true
          documentation_path: "./docs/source"

      #      - name: Run Pre-Commit Tests 🧪
      #        uses: pre-commit/action@v3.0.0

#      - name: Push changes 📌
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: pages
#          force: true
